# SwiftLint Configuration for ABC Budgeting
# Based on code standards defined in Docs/06-Quality/code-standards.md

disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - closure_body_length
  - collection_alignment
  - contains_over_filter_count
  - empty_collection_literal
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_interface_builder
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

included:
  - ABC Budgeting

excluded:
  - Pods
  - Tests
  - .build
  - DerivedData
  - .git

# Line length configuration
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

# Function body length
function_body_length:
  warning: 50
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 500

# File length
file_length:
  warning: 500
  error: 1000

# Function parameter count
function_parameter_count:
  warning: 5
  error: 8

# Type name
type_name:
  min_length: 3
  max_length: 40

# Identifier name
identifier_name:
  min_length: 1
  max_length: 40
  excluded:
    - id
    - url
    - api

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Nesting
nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

# Force unwrapping
force_unwrapping:
  severity: error

# Force casting
force_cast:
  severity: error

# Implicitly unwrapped optional
implicitly_unwrapped_optional:
  severity: error

# Empty count
empty_count:
  severity: warning

# Empty string
empty_string:
  severity: warning

# Closure body length
closure_body_length:
  warning: 30
  error: 50

# Collection alignment
collection_alignment:
  severity: warning

# Contains over filter count
contains_over_filter_count:
  severity: warning

# Empty collection literal
empty_collection_literal:
  severity: warning

# Enum case associated values count
enum_case_associated_values_count:
  warning: 5
  error: 8

# Explicit init
explicit_init:
  severity: warning

# Extension access modifier
extension_access_modifier:
  severity: warning

# Fallthrough
fallthrough:
  severity: error

# Fatal error message
fatal_error_message:
  severity: warning

# File header
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  ABC Budgeting
                    \/\/
                    \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{4}\.
                    \/\/  Copyright © \d{4} .*\. All rights reserved\.
                    \/\/

# First where
first_where:
  severity: warning

# Last where
last_where:
  severity: warning

# Literal expression end indentation
literal_expression_end_indentation:
  severity: warning

# Multiline arguments
multiline_arguments:
  severity: warning

# Multiline function chains
multiline_function_chains:
  severity: warning

# Multiline literal brackets
multiline_literal_brackets:
  severity: warning

# Multiline parameters
multiline_parameters:
  severity: warning

# Multiline parameters brackets
multiline_parameters_brackets:
  severity: warning

# Operator usage whitespace
operator_usage_whitespace:
  severity: warning

# Overridden super call
overridden_super_call:
  severity: warning

# Override in extension
override_in_extension:
  severity: warning

# Pattern matching keywords
pattern_matching_keywords:
  severity: warning

# Prefer self type over type of self
prefer_self_type_over_type_of_self:
  severity: warning

# Prefer zero over explicit init
prefer_zero_over_explicit_init:
  severity: warning

# Prohibited interface builder
prohibited_interface_builder:
  severity: error

# Prohibited super call
prohibited_super_call:
  severity: error

# Redundant nil coalescing
redundant_nil_coalescing:
  severity: warning

# Redundant type annotation
redundant_type_annotation:
  severity: warning

# Sorted first last
sorted_first_last:
  severity: warning

# Static operator
static_operator:
  severity: warning

# Strong IBOutlet
strong_iboutlet:
  severity: error

# Switch case on newline
switch_case_on_newline:
  severity: warning

# Toggle bool
toggle_bool:
  severity: warning

# Unavailable function
unavailable_function:
  severity: warning

# Unneeded parentheses in closure argument
unneeded_parentheses_in_closure_argument:
  severity: warning

# Vertical parameter alignment on call
vertical_parameter_alignment_on_call:
  severity: warning

# Vertical whitespace closing braces
vertical_whitespace_closing_braces:
  severity: warning

# Vertical whitespace opening braces
vertical_whitespace_opening_braces:
  severity: warning

# Yoda condition
yoda_condition:
  severity: warning

# Custom rules
custom_rules:
  # Enforce MARK comments for code organization
  mark_comments:
    name: "MARK Comments"
    regex: '^// MARK: - .*$'
    match_kinds:
      - comment
    severity: warning
    message: "Use MARK comments to organize code sections"

  # Enforce proper error handling
  error_handling:
    name: "Error Handling"
    regex: 'try\s+[^{]*\{[^}]*\}'
    match_kinds:
      - keyword
    severity: warning
    message: "Consider using Result type for better error handling"

  # Enforce proper documentation
  documentation:
    name: "Documentation"
    regex: '^func\s+\w+.*\{$'
    match_kinds:
      - keyword
    severity: warning
    message: "Public functions should have documentation comments"

# Reporter configuration
reporter: "xcode"
